# Sonarr Configuration
sonarr_url: 'http://localhost:8989'
sonarr_api_key: 'YOUR_SONARR_API_KEY'
skip_unmonitored: true

#General
utc_offset: +1
future_days_upcoming_shows: 60
debug: false
skip_channels: Starlight Cinema, fake trailers, Black And White Media, CircleX Creations, New Movie Updates
download_trailers: true  # Set to false to skip downloading
cleanup: true

# Path mapping (useful for Docker/unRAID environments)
  # Map Sonarr's internal paths to actual filesystem paths
  # Format: sonarr_path: actual_path
path_mapping:
  "/tv": "/mnt/user/media/tv"

collection_upcoming_shows:
  collection_name: "Coming Soon"
  smart_label: release.asc
  sort_title: "+1_2Coming Soon"
  ignore_blank_results: true
  
# Upcoming shows backdrop overlay
backdrop_upcoming_shows:
  enable: true
  back_color: "#228B22"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

# Upcoming shows text overlay  
text_upcoming_shows:
  use_text: "PREMIERES"
  date_format: "ddd dd/mm"
  capitalize_dates: true
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"